// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv7rOlwHTs_Yr1S3IeGWrBtIuPFaeg-Sw',
    appId: '1:1051740998709:web:ea3b1b9030c73db3a9357c',
    messagingSenderId: '1051740998709',
    projectId: 'interviewapp-a7df2',
    authDomain: 'interviewapp-a7df2.firebaseapp.com',
    databaseURL: 'https://interviewapp-a7df2-default-rtdb.firebaseio.com',
    storageBucket: 'interviewapp-a7df2.firebasestorage.app',
    measurementId: 'G-X96NMWJ4GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx312yFqpVr6ri4b0TzdYqchEqG5iGBXg',
    appId: '1:1051740998709:android:bd4e3f42ead754dfa9357c',
    messagingSenderId: '1051740998709',
    projectId: 'interviewapp-a7df2',
    databaseURL: 'https://interviewapp-a7df2-default-rtdb.firebaseio.com',
    storageBucket: 'interviewapp-a7df2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK6geYDSfnFPB8vTiMzh1WUejo1MX4wv4',
    appId: '1:1051740998709:ios:a0d24a06c22950b1a9357c',
    messagingSenderId: '1051740998709',
    projectId: 'interviewapp-a7df2',
    databaseURL: 'https://interviewapp-a7df2-default-rtdb.firebaseio.com',
    storageBucket: 'interviewapp-a7df2.firebasestorage.app',
    iosBundleId: 'com.example.aiInterviewApp',
  );
}
